baseURL: "http://islamtruth.org/"
languageCode: "en-us"
title: "Truth about Islam"
theme: "hugo-smorg"
author: 
    name: "Mustafa Khan"
    email: "mustafa@islamtruth.org"
copyright: "&copy; Mustafa Khan"

enableGitInfo: false
summaryLength: 20
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true
paginate: 10  # you'll want a higher, reasonable number

params: 
    debug: false # cause template path to be output at top of page, handy for dev
    #cssPath: 'css/smorg.css' # Default, override here
    #only_feed_summaries: true
    fullname: "Asalam alaikum!"
    #description: "160 characters or less describing you or your organization or your site's purpose."
    # Further customize logo in partials/logo.html; 
    # used in partials nav.html and footer.
    logotype: '<span class="has-text-weight-bold">islam<span class="has-text-danger">truth</span>.org</span>' 
    #footer: 'An open source theme by <a href="https://mikewatkins.ca/">Mike Watkins</a>'
    footer: 'Made with love by '
    #subfooter: '<i class="fab fa-github"></i> <a href="https://github.com/solutionroute/hugo-smorg">github.com/solutionroute/hugo-smorg</a>'
    subfooter: 'Copyright 2018'
        # Schema.org
    publisher:
        # Organization, Person
        type: Organization
        name: IslamTruth
        logo: url to logo image
# Primary Navigation Menu (partials/nav.html) ----------------------------
# Our exampleSite menu exploses About, Projects and Blog
# Note that "About" is added to the menu within content/about.md - it's 
# not a true "section" like post and project, although you can change this.

# NOTE: Don't put leading "/" in the url parameter
menu:
    sectionmenu:
        - name: "Islam"
          url: "islam"
          weight: 10
        - name: "Resources"
          url: "resource/"
          identifier: "resource"
          weight: 20
        - name: "Controversies"
          url: "controversy/"
          identifier: "controversy"
          weight: 30
        - name: "News"
          url: "post"
          weight: 40
        - name: "About"
          url: "about"
          weight: 50
        # Other single pages not within a section folder can be  
        # added to this menu in front matter of the document i.e. contact.md

# Syndication feeds atom.xml and rss.xml ---------------------------------
# Adds Atom feed support in conjunction with /layouts/index.atom.xml
# Change default rss filename to rss.xml, layout is built in to Hugo 
mediaTypes:
  application/atom:
    suffix: xml

outputFormats:
  Atom:
    mediaType: application/atom
    baseName: atom
  RSS:
    mediaType: application/rss
    baseName: rss

outputs:
  home:
    - HTML
    - Atom
    - RSS
